### ISSUE TITLE
Как удалить экземпляр слайдера (или отключить слайдер)? 

### ISSUE THREAD

**Issue by artemijeka** [itchief/ui-components#12]
Это надо например чтобы отключить слайдер на больших разрешениях и включать на малых.

**Comment by itchief** [comment]
Добавил метод dispose().
1, Получить экземпляр класса ItcSlider, например, с помощью статического метода getOrCreateInstance:
`const slider = ItcSlider.getOrCreateInstance('.irc-slider');`
2. Удалить экземпляр ItcSlider и все привязанные события:
`slider.dispose();`
