### ISSUE TITLE
Не работает слайдер в сафари

### ISSUE THREAD

**Issue by b1411** [itchief/ui-components#15]

**Comment by itchief** [comment]
В какой версии Safari не работает?

**Comment by agrippinos** [comment]
Тоже в сафари не работает. Версия 11.1.2

**Comment by agrippinos** [comment]
не работает в сафари на iphone IOS 15.4. На этом же iphone работает в хроме

**Comment by itchief** [comment]
Какая проблема на iphone IOS 15.4? Для сафари 11.1.2 нужно код преобразовывать с помощью Babel под этот браузер.

**Comment by agrippinos** [comment]
на iphone IOS 15.4 так же не работает и вызывает блокировку дальнейшего js кода

**Comment by agrippinos** [comment]
спасибо за подсказку, после преобразования через babel работает и на сафари 11.1.2 и на iphone
