### ISSUE TITLE
Лишние две скобки?

### ISSUE THREAD

**Issue by e1uone** [itchief/ui-components#3]
День добрый, **спасибо** за замечательный слайдер.
Единственное, что у меня возник конфликт с этими скобками, нужны ли они? На них компилятор ругается, убрал заработало всё.
https://github.com/itchief/ui-components/blob/master/ChiefSlider/chief-slider.js
![image](https://user-images.githubusercontent.com/88493974/140717826-4ad6fa30-652e-494a-9a8a-d56cd6f885a7.png)

**Comment by alex1031alex** [comment]
Это IIFE. Почитайте здесь: 
https://developer.mozilla.org/ru/docs/Glossary/IIFE
