### ISSUE TITLE
minTranslate или всё-таки max ?

### ISSUE THREAD

**Issue by alex1031alex** [itchief/ui-components#4]
В слайдере на строке 254 точно ли должно быть this._minTranslate? Логичнее выглядит this._maxTranslate.
![image](https://user-images.githubusercontent.com/30773336/141688096-c7eef906-6e6f-49e8-a283-e0ba0877c577.png)

**Comment by itchief** [comment]
Да, это ошибка. Должно быть this._maxTranslate.
