### ISSUE TITLE
Мигание слайдера в Сафари

### ISSUE THREAD

**Issue by vadimkozin** [itchief/ui-components#7]
Здравствуйте!
Попробовал пример в index.htm.  В  Сафари (Версия 15.4 (17613.1.17.1.6))  наблюдается белая вспышка при смене слайдов. Не на каждом слайде, а где-то через 2. В Хроме и Файрфоксе всё нормально.

**Comment by itchief** [comment]
Добрый день! Скриншот можете приложить и если имеются ошибки в консоли, то их тоже.

**Comment by vadimkozin** [comment]
В консоле всё чисто. Вот запись: https://monosnap.com/file/vM5rfgnKQctqTVvifLj7BpQSHApgwW

**Comment by itchief** [comment]
На тестовом стенде такого бага нет. Вот запись: https://drive.google.com/file/d/1Koiu444QYhpy9NKOTIfbXcAc_bvSLIdP/view
Попробуйте на вкладке Элементы для элементов `.itcss` и `.itcss__wrapper` отключить `overflow: hidden` и сделать ещё одну запись:
`.itcss {
  position: relative;
  /* overflow: hidden; */
  max-width: 600px;
  margin-left: auto;
  margin-right: auto;
}
.itcss__wrapper {
  position: relative;
  /* overflow: hidden; */
  background-color: #eee;
}`

**Comment by itchief** [comment]
Пока хотя бы нужно понять в чём проблема. Это конечно не решение. А если у одного из элементов отключить overflow: hidden, например, сначала, например у первого (.itcss), а потом у первого включить и выключить у второго (.itcss__wrapper). Интересно какой будет результат?

**Comment by itchief** [comment]
@vadimkozin, отлично! Тогда можете прислать pr для исправления этого бага и положить себе плюсик как разработчику.

**Comment by vadimkozin** [comment]
Послал PR.

**Comment by itchief** [comment]
Да, принял. Есть идея, как код слайдера можно очень сильно улучшить. На днях это сделаю. Интересно было бы протестировать на мерцания в Сафари. Так как сейчас можно убрать ту поддержку, которую добавлял для совместимости со старыми браузерами. Правда придется многое переписать, но производительность должна очень сильно улучшиться.

**Comment by vadimkozin** [comment]
Хорошо, протестирую.

**Comment by itchief** [comment]
@vadimkozin, создал файлы с суффиксами **dev**: `index.dev.html`, `simple-adaptive-slider.dev.css`, `simple-adaptive-slider.dev.js`. Хотел вообще по-другому логику зацикливания организовать, но там вылезли свои сложности. Не факт что лучше будет. Но код значительно оптимизировал, где мог по максимуму переписал так, чтобы браузер не вызывал Reflow.

А зачем в translate3d по z указывать 0.00001px? Для чего это?

**Comment by vadimkozin** [comment]
В интернете прочитал - это для того чтобы умный браузер не оптимизировал - не превращал translate3d(x,0,0) в translateX(x).  0.00001px по z - по сути ничего не значит, но это не 0 и браузер оптимизировать не будет. Также пишут, что трюк с заменой translateX на translate3d это мол так раньше делали для того чтобы заставить браузер отрисовку делать в GPU а не в CPU. А сейчас есть свойство CSS will-change. Мол достаточно написать will-change='transform' перед трасформацией и браузер  заранее будет знать что скоро будет transform.  Я сначала так и сделал, но Сафари этого было недостаточно (?) и оставалось мерцание при переключении слайдов , поэтому следующей строчкой прописал translate3d и Сафари остался доволен. Поэтому и в остальных местах сделал также чтобы было всё по одной схеме.

**Comment by vadimkozin** [comment]
файлы с суффиксами **dev**
Сафари (Версия 15.4 (17613.1.17.1.6))
1) изначально
https://monosnap.com/file/MzF1cfIS8eWceBBiyySeB4anyWquW9

что бросается в глаза:
a) мерцание при переходе слайдов
b) индикаторы добавляются с опозданием
с) стрелки < >  добавляются с опозданием

2) заменил одну строку в функции _move():
строка 156
_было_:  this._elItems.style.transform = `translate3D(${valueX}px, 0px, 0px)`;
_стало_: this._elItems.style.transform = `translate3D(${valueX}px, 0px, 0.0001px)`;

и вот результат:
https://monosnap.com/file/jCcoc0YRHnREEy94Ev9Xvml98LT3Hz

**Comment by itchief** [comment]
Спасибо большое. Про свойство `will-change` это понятно. Да, Safari как-то оптимизирует и тут не важно CPU или GPU, ну почти не важно. То есть, если убрать `overflow: hidden`, то он видит, что там что-то ещё есть и перестаёт это делать. Даже пока гуглил тему про мерцание, нашел, что такой же баг имеется в swiper для браузера Safari и там он не решён.

Ну вообще, тема с мерцанием в Safari – очень обсуждаемая. У меня имеется тестовый стенд с Safari. Но там всё нормально. Просто интересно, может это зависит от каких-то настроек в операционной системе или в браузере. Например, в Windows в системных настройках можно отключить анимацию.

Инфы про установку по Z значения отличного от 0 не нашёл. Это отличное решение, которое заставляет убрать Safari его оптимизации.

А почему не поставить, например, 0.1px (в js-файле с суффиксом dev так сделал).  Это тоже почти 0. И писать так короче:
`this._elItems.style.transform = translate3D(${valueX}px, 0px, 0.1px);`

Или в 0.0001px имеется какой-то смысл? Интересно было бы узнать результат с 0.1px.

**Comment by vadimkozin** [comment]
0.1px работает. Я так понимаю любое значение >0. ЧТобы не было оптимизации  translate3d в translateX.

В macOS не нашёл способа отключать анимацию.  Наверное её и нет, так как другие браузеры : Chrome и Firefox слайдер показывают нормально.

В настройках самого Safari нет такого. Есть еще  экспериментальные функции Safari. Их очень много. Я никогда там ничего не переключаю. Сейчас включал/отключал несколько хоть как-то напоминающих  transform/animation. Результата нет.

**Comment by itchief** [comment]
Fixed #8
